language: node_js
node_js:
    - 'stable'
go:
    - '1.11.x'
    - '1.12.x'
    - stable
cache: yarn
branches:
    only:
        - master
install:
    - export GO111MODULE=on
script:
    - make install
    - make compile
    - make test
